// Copyright © 2025 Rangeproof Pty Ltd. All rights reserved.
// This file is automatically generated and maintained, do not manually edit it.
//
// stringlint:disable

public enum Constants {
    public static let token_name_short: String = "SESH"
    public static let token_name_long: String = "Session Token"
    public static let token_name_long_plural: String = "Session Tokens"
    public static let network_name: String = "Session Network"
    public static let app_name: String = "Session"
    public static let session_download_url: String = "https://getsession.org/download"
    public static let price_data_powered_by: String = "Price data powered by CoinGecko"
    public static let staking_reward_pool: String = "Staking Reward Pool"
    public static let gif: String = "GIF"
    public static let session_network_url: String = "https://getsession.org/network"
    public static let session_staking_url: String = "https://token.getsession.org/staking"
}
