// Copyright © 2025 Rangeproof Pty Ltd. All rights reserved.
// This file is automatically generated and maintained, do not manually edit it.
//
// stringlint:disable

public enum Constants {
    public static let app_name: String = "Session"
    public static let session_download_url: String = "https://getsession.org/download"
    public static let gif: String = "GIF"
    public static let oxen_foundation: String = "Oxen Foundation"
}
